In [12]:
# SVM CLASSIFIER

import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

iris=datasets.load_iris()

X=iris["data"][:,(2,3)]
y=(iris["target"]==2).astype(np.float64)

svm_clf=Pipeline((("scaler",StandardScaler()),("linear_svc",LinearSVC(C=1,loss="hinge")),))

svm_clf.fit(X,y)
svm_clf.predict([[5.5,1.7]])

array([1.])

In [19]:
from sklearn.preprocessing import PolynomialFeatures
# adding polynomial features for easier linear seperation
polynomial_svm_clf=Pipeline((
                    ("poly_features",PolynomialFeatures(degree=3)),
                    ("scaler",StandardScaler()),
                    ("svm_clf",LinearSVC(C=10,loss="hinge"))))

polynomial_svm_clf.fit(X,y)
polynomial_svm_clf.predict([[5.5,1.7]])

array([1.])

In [21]:
from sklearn.svm import SVC
# kernel is used to implement poly features without actually adding features
poly_kernel_svc_clf=Pipeline((
                            ("scaler",StandardScaler()),
                            ("svm_clf",SVC(kernel="poly",degree=3,coef0=1,C=5))
                    ))
poly_kernel_svc_clf.fit(X,y)
poly_kernel_svc_clf.predict([[5.5,1.7]])

array([1.])

In [24]:
# Guassian RBF kernel -- similar to polynomial for adding higher dimensional features which makes the data easier for linear seperation
# x= e^ ( gamma * (landmark)^2 )

rbf_kernel_svm_clf=Pipeline((
                            ("scaler",StandardScaler()),
                            ("svm_clf",SVC(kernel="rbf",gamma=5,C=0.001))
))


rbf_kernel_svm_clf.fit(X,y)
rbf_kernel_svm_clf.predict([[5.5,1.7]])# predicts wrong

array([0.])

In [34]:
# SVM REGRESSOR

from sklearn.svm import LinearSVR

svm_reg=LinearSVR(epsilon=1.5)
svm_reg.fit(X,y)

LinearSVR(C=1.0, dual=True, epsilon=1.5, fit_intercept=True,
          intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
          random_state=None, tol=0.0001, verbose=0)

In [36]:
from sklearn.svm import SVR

svm_poly_reg=SVR(kernel="poly",degree=2,C=100,epsilon=0.1)
svm_poly_reg.fit(X,y)

c:\users\sai\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=100, cache_size=200, coef0=0.0, degree=2, epsilon=0.1,
    gamma='auto_deprecated', kernel='poly', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)